import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "./api";
import { Header } from "./components";
import TranslationsProvider from "../../i18nProvider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale || "en"}>
      <body>
        <QueryClientProvider client={queryClient}>
          <TranslationsProvider locale={locale}>
            <Header />
            <main>{children}</main>
          </TranslationsProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
